### ISSUE TITLE
Error: Cannot find module 'next'

### ISSUE THREAD

**Issue by Tzikas** [nmaro/staart#22]
Great project!  When I try to run `yarn dev` in the samples folder I get 

``` $ yarn dev 
yarn run v1.9.2
$ node index.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'next'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Squirrel/Documents/Code/APOLLO/staart/examples/staart/index.js:1:76)
```

I've tried `yarn install` in both the examples/staart folder and the root folder of the project.

**Comment by nickredmark** [comment]
strange, I just did the following:
```
git clone https://github.com/nmaro/staart
cd staart/examples/staart
cp settings.dist.js settings.js
cp public-settings.dist.js public-settings.js
yarn
yarn dev
```

It started without problems.

I am using node v10.9.0

**Comment by Tzikas** [comment]
That was it. 

error ooth@2.3.0: The engine "node" is incompatible with this module. Expected version ">= 10.9.0".
error Found incompatible module

I needed to update my node

**Comment by nickredmark** [comment]
Thanks for reporting back.
